/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.carwash.gui.view.admin;

import com.carwash.gui.repository.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class HomePage extends javax.swing.JFrame {
    public Connection conn; // koneksi database
    public PreparedStatement pst; // masukin query/command/perintah database
    public ResultSet rs; // menampung hasil query
    public DefaultTableModel model;
    
    private int admin_id;
    
    public HomePage() {
        initComponents();
    }
    
    public HomePage(String username, int admin_id) {
        initComponents();
        this.admin_id = admin_id;
        
        showTransactionTable();
        
        greetingLabelAdmin.setText("Halo, " + username);
    }
    
    public void showTransactionTable() {
        String[] table_header = {"No.", "Code", "Customer", "Car Type", "Wash Type", "Total", "Status"};
        model = new DefaultTableModel(table_header, 0);
        transactionTable.setModel(model);
        try {
            conn = DatabaseConnection.getConnection();
            pst = conn.prepareStatement("SELECT t.transaction_id, t.customer_id, c.name AS customer_name, car.type AS car_type, car.cost AS car_cost, cat.category AS category_name, cat.price AS category_price, t.total, t.status FROM tb_transactions t INNER JOIN tb_customers c ON t.customer_id = c.customer_id INNER JOIN tb_cars car ON t.car_id = car.car_id INNER JOIN tb_categories cat ON t.category_id = cat.category_id WHERE t.status = 'In queue' OR t.status = 'Washing' ORDER BY t.transaction_id ASC;");
            rs = pst.executeQuery();
            
            int no = 1;
            while (rs.next()) {
                String[] transactionRow = {Integer.toString(no), rs.getString(1), rs.getString(3), rs.getString(4), rs.getString(6), rs.getString(8), rs.getString(9)};
                model.addRow(transactionRow);
                no++;
            }
            transactionTable.setModel(model);
            
        } catch (Exception ex) {
            System.out.print(ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        confirmTransactionMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        deleteAllDataMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logoutMenu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        confirmCarMenu = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        greetingLabelAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page - Admin");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        confirmTransactionMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmTransactionMenuMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Confirm Transaction");

        javax.swing.GroupLayout confirmTransactionMenuLayout = new javax.swing.GroupLayout(confirmTransactionMenu);
        confirmTransactionMenu.setLayout(confirmTransactionMenuLayout);
        confirmTransactionMenuLayout.setHorizontalGroup(
            confirmTransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmTransactionMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        confirmTransactionMenuLayout.setVerticalGroup(
            confirmTransactionMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        deleteAllDataMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAllDataMenuMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Delete All Data");

        javax.swing.GroupLayout deleteAllDataMenuLayout = new javax.swing.GroupLayout(deleteAllDataMenu);
        deleteAllDataMenu.setLayout(deleteAllDataMenuLayout);
        deleteAllDataMenuLayout.setHorizontalGroup(
            deleteAllDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteAllDataMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        deleteAllDataMenuLayout.setVerticalGroup(
            deleteAllDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteAllDataMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMenuMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Logout");

        javax.swing.GroupLayout logoutMenuLayout = new javax.swing.GroupLayout(logoutMenu);
        logoutMenu.setLayout(logoutMenuLayout);
        logoutMenuLayout.setHorizontalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoutMenuLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(76, 76, 76))
        );
        logoutMenuLayout.setVerticalGroup(
            logoutMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Documents\\NetBeansProjects\\CarWash\\src\\main\\java\\com\\carwash\\gui\\assets\\images\\logo.png")); // NOI18N

        confirmCarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmCarMenuMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Confirm Car");

        javax.swing.GroupLayout confirmCarMenuLayout = new javax.swing.GroupLayout(confirmCarMenu);
        confirmCarMenu.setLayout(confirmCarMenuLayout);
        confirmCarMenuLayout.setHorizontalGroup(
            confirmCarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmCarMenuLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        confirmCarMenuLayout.setVerticalGroup(
            confirmCarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteAllDataMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmTransactionMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmCarMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(confirmTransactionMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmCarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteAllDataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 600));

        transactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Code", "Customer", "Car Type", "Wash Type", "Total", "Status"
            }
        ));
        transactionTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transactionTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 550, 370));

        greetingLabelAdmin.setFont(new java.awt.Font("Roboto", 1, 30)); // NOI18N
        greetingLabelAdmin.setText("Halo, Admin!");
        getContentPane().add(greetingLabelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmTransactionMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmTransactionMenuMouseClicked
        // TODO add your handling code here:
        String confirmTransactionCode = JOptionPane.showInputDialog("Confirm Transaction");
        try {
            conn = DatabaseConnection.getConnection();
            pst = conn.prepareStatement("UPDATE tb_transactions SET status = 'Confirmed' WHERE transaction_id = ?");
            pst.setString(1, confirmTransactionCode);
            int up = pst.executeUpdate(); 
            if (up == 1) {
                JOptionPane.showMessageDialog(this, "Data success to confirm");
            } else {
                JOptionPane.showMessageDialog(this, "Data failed to confirm!");
            }
            showTransactionTable();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_confirmTransactionMenuMouseClicked

    private void deleteAllDataMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAllDataMenuMouseClicked
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Are you sure to delete all transaction data?", 
                    "Delete All Data", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
            
        if(jawab == JOptionPane.YES_OPTION){
            try {
            conn = DatabaseConnection.getConnection();
            pst = conn.prepareStatement("DELETE FROM tb_transactions");
            int up = pst.executeUpdate(); // 1 0
            
            if (up == 0) {
                JOptionPane.showMessageDialog(this, "All data success to deleted!");
            } else {
                JOptionPane.showMessageDialog(this, "Data failed to deleted!");
            }
            showTransactionTable();
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            }
        }
        
    }//GEN-LAST:event_deleteAllDataMenuMouseClicked

    private void logoutMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseClicked
        // TODO add your handling code here:
        int logout = JOptionPane.showOptionDialog(this, 
                    "Do you want to logout?", 
                    "Logout", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
            
        if(logout == JOptionPane.YES_OPTION){
            this.dispose();
            LoginAdmin loginAdmin = new LoginAdmin();
            loginAdmin.setVisible(true);
        }
    }//GEN-LAST:event_logoutMenuMouseClicked

    private void confirmCarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmCarMenuMouseClicked
        // TODO add your handling code here:
        String car_code = JOptionPane.showInputDialog("Confirm Car Code");
        try {
            conn = DatabaseConnection.getConnection();
            pst = conn.prepareStatement("UPDATE tb_transactions SET status = 'Washing' WHERE transaction_id = ?");
            pst.setString(1, car_code);
            int nilai = pst.executeUpdate(); // 1 0
            
            if (nilai == 1) {
                JOptionPane.showMessageDialog(this, "Data successfully updated!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update!");
            }
            showTransactionTable();
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_confirmCarMenuMouseClicked

    private void transactionTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionTableMouseClicked
        // TODO add your handling code here:
        showTransactionTable();
    }//GEN-LAST:event_transactionTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel confirmCarMenu;
    private javax.swing.JPanel confirmTransactionMenu;
    private javax.swing.JPanel deleteAllDataMenu;
    private javax.swing.JLabel greetingLabelAdmin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutMenu;
    private javax.swing.JTable transactionTable;
    // End of variables declaration//GEN-END:variables
}
